final code V2

diff --git a/.github/workflows/automate.yml b/.github/workflows/automate.yml
--- a/.github/workflows/automate.yml
+++ b/.github/workflows/automate.yml
@@ -38,26 +38,55 @@ jobs:
 #          name: Build-Runner-Artifacts
 #          path: Build-Runner-Artifacts
 #
-  Publish-Artifacts-Stable-Branch:
-    name: Publish Artifacts (Stable Branch)
+  Publish-Stable-Branch-Artifacts:
+    name: Publish Stable Branch Artifacts
     runs-on: ubuntu-latest
     container: docker:20.10.7
     needs:
       - Build-and-Package
-#      - Container-Image-Scan
     if: github.ref == 'refs/heads/main'
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Ensure full history is fetched, useful for Git operations during publish.
       - name: Download Artifacts
         uses: actions/download-artifact@v3
         with:
           name: Build-Runner-Artifacts
-          path: ./Build-Runner-Artifacts/  # Directory where artifacts will be downloaded.
+          path: ./Build-Runner-Artifacts/
       - name: Publish
-        run: sh ./automate.sh --Target Publish
+        run: |
+          echo "Publishing artifacts..."
+          if [ -d ./Build-Runner-Artifacts/ ]; then
+            sh ./automate.sh --Target Publish
+          else
+            echo "❌ Build-Runner-Artifacts not found. Cannot proceed with publishing."
+            exit 1
+          fi
       - name: Clean Workspace
         run: sh ./automate.sh --Target CleanWorkspace
+#
+#  Publish-Artifacts-Stable-Branch:
+#    name: Publish Artifacts (Stable Branch)
+#    runs-on: ubuntu-latest
+#    container: docker:20.10.7
+#    needs:
+#      - Build-and-Package
+##      - Container-Image-Scan
+#    if: github.ref == 'refs/heads/main'
+#    steps:
+#      - name: Checkout Code
+#        uses: actions/checkout@v3
+#      - name: Download Artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: Build-Runner-Artifacts
+#          path: ./Build-Runner-Artifacts/  # Directory where artifacts will be downloaded.
+#      - name: Publish
+#        run: sh ./automate.sh --Target Publish
+#      - name: Clean Workspace
+#        run: sh ./automate.sh --Target CleanWorkspace
 #
 #  Publish-Artifacts-UnStable-Branch:
 #    name: Publish Artifacts (Unstable Branch)
